# Generated by Django 6.0.2 on 2026-03-05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0004_add_prediction_cache_fields"),
        ("eda", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="StockTimeSeriesPrediction",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("stock_symbol", models.CharField(max_length=20)),
                ("current_price", models.FloatField()),
                ("ts1", models.FloatField()),
                ("ts2", models.FloatField()),
                ("ts3", models.FloatField()),
                ("ts4", models.FloatField()),
                ("ts5", models.FloatField()),
                ("ts6", models.FloatField()),
                ("ts7", models.FloatField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("portfolio", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="timeseries_predictions", to="portfolio.portfolio")),
            ],
            options={
                "db_table": "stock_timeseries_predictions",
            },
        ),
    ]
