# Generated by Django 6.0.2 on 2026-03-03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="portfolio",
            name="sector",
        ),
        migrations.AddField(
            model_name="portfolio",
            name="description",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AlterField(
            model_name="stock",
            name="ticker",
            field=models.CharField(max_length=20),
        ),
        migrations.AlterUniqueTogether(
            name="stock",
            unique_together={("portfolio", "ticker")},
        ),
    ]
