# Generated by Django 6.0.2 on 2026-03-03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0002_update_portfolio_and_stock_constraints"),
    ]

    operations = [
        migrations.AddField(
            model_name="stock",
            name="high_52w",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="stock",
            name="low_52w",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
