# Generated by Django 6.0.2 on 2026-03-06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0004_add_prediction_cache_fields"),
    ]

    operations = [
        migrations.CreateModel(
            name="TimeSeriesForecast",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("forecast_type", models.CharField(max_length=10)),
                (
                    "horizon_days",
                    models.IntegerField(
                        choices=[(1, "ts_1"), (7, "ts_7")],
                    ),
                ),
                ("model_name", models.CharField(default="ARIMA", max_length=50)),
                ("predicted_for_date", models.DateField()),
                ("forecast_prices", models.JSONField(blank=True, default=list)),
                ("history_prices", models.JSONField(blank=True, default=list)),
                ("history_dates", models.JSONField(blank=True, default=list)),
                ("forecast_dates", models.JSONField(blank=True, default=list)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "stock",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="timeseries_forecasts",
                        to="portfolio.stock",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "unique_together": {("stock", "forecast_type", "predicted_for_date")},
            },
        ),
    ]
